- type: entity
  parent: RDEntity
  id: RDItem
  abstract: true
  components:
  - type: Animateable
  - type: Clickable
  - type: InteractionOutline
  - type: Item
    size: Small
  - type: Sprite
    drawdepth: Items
    noRot: false
  - type: Physics
    bodyType: Dynamic
    fixedRotation: false
  - type: Pullable
  - type: CollisionWake
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-0.25,-0.25,0.25,0.25"
        density: 20
        mask:
        - ItemMask
        restitution: 0.3
        friction: 0.2
