- type: entity
  save: false
  parent:
  - BaseMob
  - MobDamageable
  - MobPolymorphable
  - MobCombat
  - StripableInventoryBase
  id: RDBaseMobSpecies
  abstract: true
  components:
  - type: Inventory
    templateId: RDMain
  - type: HumanoidAppearance
    species: RDHuman
  - type: Sprite
    layers:
    - map: ["enum.HumanoidVisualLayers.Chest"]
    - map: ["enum.HumanoidVisualLayers.Head"]
    - map: ["enum.HumanoidVisualLayers.Snout"]
    - map: ["enum.HumanoidVisualLayers.Eyes"]
    - map: ["enum.HumanoidVisualLayers.RLeg"]
    - map: ["enum.HumanoidVisualLayers.LLeg"]
    - map: ["pants"]
    - map: ["enum.HumanoidVisualLayers.RArm"]
    - map: ["enum.HumanoidVisualLayers.LArm"]
    - map: ["enum.HumanoidVisualLayers.UndergarmentBottom"]
    - map: ["enum.HumanoidVisualLayers.UndergarmentTop"]
    - map: ["shoes"]
    - map: ["shirt"]
    - map: ["gloves"]
    - map: ["ears"]
    - map: ["eyes"]
    - map: ["belt"]
    - map: ["id"]
    - map: ["outerClothing"]
    - map: ["back"]
    - map: ["neck"]
    - map: ["enum.HumanoidVisualLayers.FacialHair"]
    - map: ["enum.HumanoidVisualLayers.Hair"]
    - map: ["enum.HumanoidVisualLayers.HeadSide"]
    - map: ["enum.HumanoidVisualLayers.HeadTop"]
    - map: ["enum.HumanoidVisualLayers.Tail"]
    - map: ["mask"]
    - map: ["head"]
    - map: ["pocket1"]
    - map: ["pocket2" ]
  - type: DamageVisuals
    thresholds: [ 10, 20, 30, 50, 70, 100 ]
    targetLayers:
    - "enum.HumanoidVisualLayers.Chest"
    - "enum.HumanoidVisualLayers.Head"
    - "enum.HumanoidVisualLayers.LArm"
    - "enum.HumanoidVisualLayers.LLeg"
    - "enum.HumanoidVisualLayers.RArm"
    - "enum.HumanoidVisualLayers.RLeg"
    damageOverlayGroups:
      Brute:
        sprite: Mobs/Effects/brute_damage.rsi
        color: "#FF0000"
      Burn:
        sprite: Mobs/Effects/burn_damage.rsi
  - type: RotationVisuals
    defaultRotation: 90
    horizontalRotation: 90
  - type: SlowOnDamage
    speedModifierThresholds:
      60: 0.7
      80: 0.5
  - type: Fixtures
    fixtures: # TODO: This needs a second fixture just for mob collisions.
      fix1:
        shape:
          !type:PhysShapeCircle
          radius: 0.35
        density: 185
        restitution: 0.0
        mask:
        - MobMask
        layer:
        - MobLayer
  - type: FloorOcclusion
  - type: RangedDamageSound
    soundGroups:
      Brute:
        collection:
          MeatBulletImpact
    soundTypes:
      Heat:
        collection:
          MeatLaserImpact
  - type: Reactive
    groups:
      Flammable: [ Touch ]
      Extinguish: [ Touch ]
      Acidic: [Touch, Ingestion]
    reactions:
    - reagents: [Water, SpaceCleaner]
      methods: [Touch]
      effects:
      - !type:WashCreamPieReaction
  - type: StatusEffects
    allowed:
    - Stun
    - KnockedDown
    - SlowedDown
    - Stutter
    - SeeingRainbows
    - Electrocution
    - Drunk
    - SlurredSpeech
    - RatvarianLanguage
    - PressureImmunity
    - Muted
    - ForcedSleep
    - TemporaryBlindness
    - Pacified
    - StaminaModifier
    - Flashed
    - RadiationProtection
    - Drowsiness
    - Adrenaline
  - type: Body
    prototype: RDHuman
    requiredLegs: 2
  - type: Hands
  - type: ComplexInteraction
  - type: Internals
  - type: FloatingVisuals
  - type: Climbing
  - type: Ensnareable
    sprite: Objects/Misc/ensnare.rsi
    state: icon
  - type: AnimationPlayer
  - type: Buckle
  - type: CombatMode
    canDisarm: true
  - type: MeleeWeapon
    soundHit:
      collection: Punch
    angle: 30
    animation: WeaponArcFist
    attackRate: 1
    damage:
      types:
        Blunt: 5
  - type: SleepEmitSound
  - type: StandingState
  - type: MindContainer
    showExamineInfo: true
  - type: Stripping
  - type: UserInterface
    interfaces:
      enum.HumanoidMarkingModifierKey.Key:
        type: HumanoidMarkingModifierBoundUserInterface
      enum.StrippingUiKey.Key:
        type: StrippableBoundUserInterface
  - type: Puller
  - type: Speech
    speechSounds: Alto
  - type: DamageForceSay
  - type: Vocal
    sounds:
      Male: MaleHuman
      Female: FemaleHuman
      Unsexed: MaleHuman
  - type: Emoting
  - type: BodyEmotes
    soundsId: GeneralBodyEmotes
  - type: Grammar
    attributes:
      proper: true
  - type: Tag
    tags:
    - FootstepSound
    - DoorBumpOpener

- type: entity
  parent:
  - MobBloodstream
  - MobRespirator
  - MobAtmosStandard
  - MobFlammable
  - RDBaseMobSpecies
  id: RDBaseMobSpeciesOrganic
  save: false
  abstract: true
  components:
  - type: RDDeathScreen
  - type: RDCharacteristicContainer
  - type: RDPerkContainer
  - type: RDWeight
  - type: Icon
    sprite: _RD/Entities/Player/Human/parts.rsi
    state: full
  - type: PassiveDamage # Slight passive regen. Assuming one damage type, comes out to about 4 damage a minute.
    allowedStates:
    - Alive
    damageCap: 20
    damage:
      types:
        Heat: -0.07
      groups:
        Brute: -0.07
  - type: Blindable
  # Other
  - type: Temperature
    heatDamageThreshold: 325
    coldDamageThreshold: 260
    currentTemperature: 310.15
    specificHeat: 42
    coldDamage:
      types:
        Cold: 0.1 #per second, scales with temperature & other constants
    heatDamage:
      types:
        Heat: 1.5 #per second, scales with temperature & other constants
  - type: TemperatureSpeed
    thresholds:
      293: 0.8
      280: 0.6
      260: 0.4
  - type: ThermalRegulator
    metabolismHeat: 800
    radiatedHeat: 100
    implicitHeatRegulation: 500
    sweatHeatRegulation: 2000
    shiveringHeatRegulation: 2000
    normalBodyTemperature: 310.15
    thermalRegulationTemperatureThreshold: 2
  - type: Perishable
  - type: Respirator
    damage:
      types:
        Asphyxiation: 1.0
    damageRecovery:
      types:
        Asphyxiation: -1.0
  - type: FireVisuals
    alternateState: Standing

- type: entity
  id: RDBaseSpeciesDummy
  parent: InventoryBase
  save: false
  abstract: true
  components:
  - type: Hands
  - type: ComplexInteraction
  - type: ContainerContainer
  - type: Icon
    sprite: _RD/Entities/Player/Human/parts.rsi
    state: full
  - type: Sprite
    drawdepth: Mobs
    noRot: true
    layers:
    - map: ["enum.HumanoidVisualLayers.Chest"]
    - map: ["enum.HumanoidVisualLayers.Head"]
    - map: ["enum.HumanoidVisualLayers.Snout"]
    - map: ["enum.HumanoidVisualLayers.Eyes"]
    - map: ["enum.HumanoidVisualLayers.RLeg"]
    - map: ["enum.HumanoidVisualLayers.LLeg"]
    - map: ["pants"]
    - map: ["enum.HumanoidVisualLayers.RArm"]
    - map: ["enum.HumanoidVisualLayers.LArm"]
    - map: ["enum.HumanoidVisualLayers.UndergarmentBottom"]
    - map: ["enum.HumanoidVisualLayers.UndergarmentTop"]
    - map: ["gloves"]
    - map: ["shoes"]
    - map: ["shirt"]
    - map: ["ears"]
    - map: ["eyes"]
    - map: ["belt"]
    - map: ["id"]
    - map: ["outerClothing"]
    - map: ["back"]
    - map: ["neck"]
    - map: ["enum.HumanoidVisualLayers.FacialHair"]
    - map: ["enum.HumanoidVisualLayers.Hair"]
    - map: ["enum.HumanoidVisualLayers.HeadSide"]
    - map: ["enum.HumanoidVisualLayers.HeadTop"]
    - map: ["enum.HumanoidVisualLayers.Tail"]
    - map: ["mask"]
    - map: ["head"]
    - map: ["pocket1"]
    - map: ["pocket2"]
  - type: Appearance
  - type: HumanoidAppearance
    species: RDHuman
  - type: Body
    prototype: RDHuman
    requiredLegs: 2
  - type: UserInterface
    interfaces:
      enum.HumanoidMarkingModifierKey.Key:
        type: HumanoidMarkingModifierBoundUserInterface
