- type: entity
  parent: RDClothing
  id: RDClothingPants
  description: Pleasant to the touch material, in a comfortable loose pants shape.
  abstract: true
  components:
  - type: Clothing
    equipDelay: 1
    unequipDelay: 1
    slots:
    - pants
  - type: Sprite
    state: icon
